######################################################################
# Automatically generated by qmake (2.01a) Sun Dec 30 15:13:30 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
CONFIG += DEBUG

# Input
HEADERS += canvas.h vector.h raytracer.h camera.h primitives.h
SOURCES += canvas.cc main.cc raytracer.cc camera.cc
